# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y5LQJE4Ga4xKiSuQiyg4d8tfOZ4FXQRA
"""

# Install (only if needed)
!pip install pandas matplotlib scikit-learn

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Load dataset directly from GitHub (no download needed)
url = "https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv"
df = pd.read_csv(url)

# Show first 5 rows
df.head()

# Select important columns
df = df[['country', 'year', 'co2', 'co2_per_capita', 'population']]

# Drop missing values
df = df.dropna()

# Filter last 10 years
df_recent = df[df['year'] >= 2013]

df_recent.head()

latest_year = df_recent['year'].max()

top_emitters = df_recent[df_recent['year'] == latest_year] \
                .sort_values(by='co2', ascending=False).head(10)

print("Top 10 CO2 Emitting Countries:")
top_emitters[['country', 'co2']]

plt.figure()
plt.bar(top_emitters['country'], top_emitters['co2'])
plt.xticks(rotation=45)
plt.title("Top 10 CO2 Emitting Countries")
plt.xlabel("Country")
plt.ylabel("CO2 Emissions")
plt.tight_layout()
plt.show()

global_trend = df.groupby('year')['co2'].sum()

plt.figure()
plt.plot(global_trend.index, global_trend.values)
plt.title("Global CO2 Emissions Over Time")
plt.xlabel("Year")
plt.ylabel("Total CO2 Emissions")
plt.grid()
plt.show()

high_per_capita = df_recent[df_recent['year'] == latest_year] \
                    .sort_values(by='co2_per_capita', ascending=False).head(10)

print("Top 10 CO2 per capita countries:")
high_per_capita[['country', 'co2_per_capita']]

from sklearn.linear_model import LinearRegression

# Prepare data
years = global_trend.index.values.reshape(-1, 1)
emissions = global_trend.values

# Train model
model = LinearRegression()
model.fit(years, emissions)

# Predict next 10 years
future_years = np.arange(years.max()+1, years.max()+11).reshape(-1, 1)
predictions = model.predict(future_years)

# Plot
plt.figure()
plt.plot(years, emissions, label="Actual")
plt.plot(future_years, predictions, linestyle='dashed', label="Predicted")
plt.title("CO2 Emissions Prediction")
plt.xlabel("Year")
plt.ylabel("CO2 Emissions")
plt.legend()
plt.show()